### ISSUE TITLE
Move CSS over to grid

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#11]
Because: 
The table currently currently is hard to style and make responsive resulting in a bloated css. Grid would be much more suitable here.
Also, grid alone can scale down nicely own it's own so we probably don't need those media queries

Tasks: 
- [ ] Move the markup to grid
- [ ] Move CSS to grid
- [ ] Add a suitable query to change the view on phone
- [ ] Refactor the buttons setup a bit to work with the new feature

**Comment by DigitalKnight0** [comment]
@Mclilzee Not sure i fully grasp the idea? Do you have a drawing of some sort to depict it?
Btw [here's](https://digitalknight0.github.io/zap-simulator/) our progress so far (You have to open it on desktop since it's not optimized yet)

**Comment by Mclilzee** [comment]
Yeah forget about it, your new update is great i'm loving it. I'll work on responsive fonts and padding later on.
