### ISSUE TITLE
Style Zap svgs

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#12]
Because: 
We need different colored svgs to represent the offenses on each tier, we need more of them pre-styled on their own

The original one can be found [Here](https://github.com/Mclilzee/zap-simulator/blob/main/zap.svg)

Tasks
- [ ] The svgs should have different colors (5 needed)
- [ ] The color pattern should be good (I came up with red, blue, green, orange, black) but feel free to choose a more suitable
- [ ] The background should remain untouched - (If you are going for a different type other than svg, the background should either be transparent or they should have two for each in white and black background)
- [ ] The resolution and aspect ratio should remain consistent

**Comment by DigitalKnight0** [comment]
@ManonLef The max size we would go for would be 30 x 30px so i guess something around that. shouldn't be lower than that tho since it will blur out

**Comment by ManonLef** [comment]
@DigitalKnight0 that’s very small, which is perfect. If I make a PNG I’ll make a few sizes bigger too for scalability purposes. I can probably get to this in the coming week. Feel free to assign it to me @Mclilzee if that sounds good.

**Comment by Mclilzee** [comment]
@ManonLef It's all yours!

**Comment by ManonLef** [comment]
![TOP Zap](https://user-images.githubusercontent.com/81025586/153774645-2bb82f2f-3fb4-43a6-8364-7077e260d828.svg)

Can you test this little zap svg I made? Then I can make adjustments as needed before proceeding to the color scheme.

**Comment by ManonLef** [comment]
<img width="432" alt="Screenshot 2022-02-13 at 22 00 11" src="https://user-images.githubusercontent.com/81025586/153774862-b555d00c-a6c7-4a15-afdd-476977059325.png">

Here's a variation screenshot. To fill the blocks more you could also choose to go for the one on the right. Not sure how that would work with @DigitalKnight0 's stacking idea

**Comment by Mclilzee** [comment]
It looks great to me! I'm sure it gonna fit perfectly even without testing it. I'll leave it to @DigitalKnight0 to test it in his overhaul. the yellow to red looks great, this is much more pleasing than the black borders it has before.

**Comment by ManonLef** [comment]
@Mclilzee I agree, I like some sort of contrast but not necessarily black. Just enough of a hue sift would be more subtle.

With yellow to red I'm referring to the overall range of colours (so no more blue or green)

**Comment by DigitalKnight0** [comment]
@ManonLef The color scheme sounds great to me!
If you wanna test the svgs, head over to index.js and find this object
![Screenshot_2022_0214_064352](https://user-images.githubusercontent.com/93139167/153786455-d66bb1b7-5994-4295-8a72-783bdb421c7f.jpg)

Where increasing or decreasing the factor here will shift them right or left accordingly

**Comment by DigitalKnight0** [comment]
@ManonLef The color scheme looks great to me!
You can test your svgs by heading to `index.js` and replacing the filepaths here with yours 
![Screenshot_2022_0214_064352](https://user-images.githubusercontent.com/93139167/153786593-e7337f2e-57b9-4705-8791-24bab255e679.jpg)

You can shift them left or right by increasing or decreasing the factor here 
![Screenshot_2022_0214_064415](https://user-images.githubusercontent.com/93139167/153786623-b33aaae3-6a49-485c-9ddc-9bdbb48f4c40.jpg)

**Comment by ManonLef** [comment]
![Screenshot 2022-02-14 at 11 52 18](https://user-images.githubusercontent.com/81025586/153850628-01de43eb-59a7-488a-8157-7587c03b842c.png)

had a quick play with it. Let me know what you both think.

**Comment by DigitalKnight0** [comment]
@ManonLef I agree, this one definitely looks great! Thank you for doing this! 
I just had one query in mind, are the bolts not shrinking in size like the last svg?
![IMG_20220214_162559](https://user-images.githubusercontent.com/93139167/153857667-d8c9ab9a-14b3-49be-8fdf-8de960b81ae4.png)

Because i can't see the difference here

**Comment by Mclilzee** [comment]
This is great! leave it to @ManonLef to make the most amazing SVGs.

@DigitalKnight0 Yeah i don't think they are shrinking, but they do look good even without shrinking tho, I was wondering if we make them same colors as the buttons they representing, but it will then start looking like rainbow spagheti. Maybe give the buttons a single color i'm not sure if having them different colored matter much. A nice way we can also go about it, is in the buttons panel, we can make the Buttons show a number of how many points they gonna give next.

**Comment by DigitalKnight0** [comment]
@Mclilzee I do agree that it looks good in that format. However there is a slight problem with that
![IMG_20220214_173407](https://user-images.githubusercontent.com/93139167/153865265-a3064640-f373-4daa-b42a-c884d5cad90d.png)
Currently, the SVGs don't really move past beyond that point and stack to the left. This does not look odd due to shrinking effect but without it, we would have to find a way to actually shift them to the right by a factor on each addition


As for your second suggestion, i do feel like you sometimes read my mind lol. I had a similar idea
Here's my version:
Since we are no longer using different colors, and actually going dark -> light for a same one, i think that the shade could represent *tiers* rather than offenses. For e.g, a tier three tree zap would be of s darker shade than a tier 1. And with that we can change the corresponding buttons to that tier's shade and maybe add a line next to it denoting the tier.

Let me know what you think

**Comment by ManonLef** [comment]
I think the fact they don't shrink has to do with their default size and I will check to see if they shrink again if I match their default size to the old version. I just quickly pasted it in there

I suggested the yellow to red colors to represent the current color coding as follows: The different infringements get a different color exactly as they are now but instead of using blue green and whatnot it will become: yellow, light orange, orange, dark orange, red. 

I do agree that the stacking to the left might be something you want to avoid but I have no clue how many stacks you'll get. 

With this particular design however, to not make it a complete designfail: **never put them next to eachother instead of stacking them.**  It will resemble the ss logo and that's definitely undesirable.

I will make the different colors and resize them to see if they keep their shrink properties, and then do a PR so you can play around with it. 
Will try to get to it later today if I can find a spare moment :)

**Comment by DigitalKnight0** [comment]
@ManonLef I realized that the problem was related to css and not the actual svgs. However, i have to admit, it looks quite odd after fixing it
![Screenshot_2022-02-15_21-59-27(1)](https://user-images.githubusercontent.com/93139167/154111410-fd86248f-6341-4779-99e5-570d0060823a.png)
It might be due to the particular shape of those svgs. So i am thinking of dropping the idea, and find a way to shift them towards center on each iteration while keeping the same size in stacks

**Comment by DigitalKnight0** [comment]
@ManonLef I have pushed a fix to the above problem here in this [PR](https://github.com/Mclilzee/zap-simulator/pull/16). You can preview it [here](https://digitalknight0.github.io/zap-simulator/). In addition to centering them, i also made it resize the svgs a bit on each addition to they occupy a bit less space. Do let me know if that looks fine, or we can revert to just centering them. 
Also, regarding branches, i usually find working with them far more easier than managing stuff with main, but upto you! 
Do feel free to pull in the latest changes to test your svgs in your local repo (Either from my branch or when @Mclilzee merges it)

**Comment by DigitalKnight0** [comment]
As for this
> I suggested the yellow to red colors to represent the current color coding as follows: The different infringements get a different color exactly as they are now but instead of using blue green and whatnot it will become: yellow, light orange, orange, dark orange, red.

With the previous setup, the different colors actually kept the infringements apart on their own, but having a change in contrast/hue might be confusing since a darker shade would usually represent a more serious offense (Maybe, that's what comes to mind). So the new idea is to let the colors represent the tiers rather than individual infringements/offenses which might be more suitable, and then get each of them to change their shade accordingly with the tier they moved to

**Comment by ManonLef** [comment]
> With the previous setup, the different colors actually kept the infringements apart on their own, but having a change in contrast/hue might be confusing since a darker shade would usually represent a more serious offense (Maybe, that's what comes to mind). So the new idea is to let the colors represent the tiers rather than individual infringements/offenses which might be more suitable, and then get each of them to change their shade accordingly with the tier they moved to

I like this idea much better.

Since I broke discord I have time to look into it now.

**Comment by ManonLef** [comment]
Here's the updated colourscheme. I'll wait for the merge before I pull, edit and make a PR. 

![Screenshot 2022-02-15 at 20 58 48](https://user-images.githubusercontent.com/81025586/154139491-ca88f477-69f7-44c8-af39-e09857c77ec7.png)
![Screenshot 2022-02-15 at 20 59 27](https://user-images.githubusercontent.com/81025586/154139457-a7140960-13b4-4782-9171-10c4544a810c.png)
