### ISSUE TITLE
Modal cannot be closed

### ISSUE THREAD

**Issue by LeoKirasic** [Mclilzee/zap-simulator#15]
Currently, if a tier is clicked and the modal to choose an offense opens, there is no way to close it. There should either be a closing button, or the modal should close by clicking on the background. Ideally- both.

**Comment by Mclilzee** [comment]
Feel free to work on any part and just simply send a pull request. This project is yours as anyone else.

**Comment by JuanDCeballos** [comment]
I would like to give this a try, if @LeoKirasic isn't working on it right now.

**Comment by jernestmyers** [comment]
I've refactored it to close when a button isn't clicked, but haven't added a Close button. I was playing around with it but I should have made that known :/

**Comment by jernestmyers** [comment]
I'll just push those changes for now and leave it up for review and someone else can add the buttons and/or improve/discard my solution. I have to wrap up for the day anyway.

**Comment by Mclilzee** [comment]
@JuanDCeballos can you add that close button please?

**Comment by Mclilzee** [comment]
@jernestmyers ty, the pull was merged

**Comment by LeoKirasic** [comment]
The change Jeremy made is indeed useful, but having an actual closing button on top of the current functionality would be useful for the simplicity of things IMO.

**Comment by jernestmyers** [comment]
I agree! I felt bad about silently working on it so thought I'd push the first part and let @JuanDCeballos take it over from there.

**Comment by JuanDCeballos** [comment]
Thanks, I'll work on this.

Will let you know how it goes.

**Comment by Mclilzee** [comment]
@JuanDCeballos the buttons looks great!

I think if we move it to the right corner it would look more natural as people are more used to moving their mouse their by nature using muscle memories. @JuanDCeballos Would you like to work on this? also a cursor being pointer when hoving over it would give it more visibility.

**Comment by JuanDCeballos** [comment]
@Mclilzee, yeah I'll be glad to work on that.

Btw, the close button is on the right corner, where yours appear?

**Comment by Mclilzee** [comment]
@JuanDCeballos Oh wait a min... it's actually exactly what I wanted. Weird, when I first tried it the X was hovering exactly over the buttons, and it has no cursor pointer. Must be GitHub haven't fully updated it. Now i checked it, that's exactly how I had it in mind! Great job Juan <3.

 Ty all for the contribution.
