### ISSUE TITLE
Final touches

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#21]
Just leaving a list of stuff here that needs to be done so someone can pick them up and contribute if they want

- [ ] Update the wording of the buttons to better reflect the particular offenses in the matrix
- [ ] Fix font sizes (Make them more responsive)
- [x] Shift css to use variables (The variables are already made)
- [x] There is currently a small bug with dark/light mode icons where clicking on the container instead of actual svgs does not switch the icons (Pretty low chance but still exists). Can be rectified with => Adding a guard statement in the listener to check for type of svg on target before moving on
- [ ] Get a better color scheme for offense drop down modal's background/tier spans. the current gray/black looks strange. (Proposed solution is to add a blur to modal's background and change the font color on tags accordingly)
- [ ]  Reduce the size of time travel button on small viewports (currently grows too big)
- [ ] Update the title to use a better styling (Maybe switch the font)
- [ ] Change the button's hover effect from opacity to brightness/saturation
- [x] change tier 0's color scheme
- [ ] change the initial welcome message on the statBox to something more descriptive
- [ ] The offense buttons need more styling.
- [ ] Fix the positioning of time travel and reset buttons on desktop and mobile views

**Comment by DigitalKnight0** [comment]
@BlizZard-bot thank you!
Yes i do agree that seperate issues would be better. Please feel free to create them for whichever tasks you are working on!

**Comment by ManonLef** [comment]
I like what you did to the buttons in the dropdown! 
I did make a few quick adjustments in the devtools and think they may be a bit more in line with the rest of the design with a few minor adjustments.

I'm not entirely sure I can fix this myself but if you like this screenshot, I could give it a try?

changes:

- slight border radius (like the other buttons have as well)
- removed bold to match with the other type used
- enlarged the button font-size to 12

Let me know what you think!
![Screenshot 2022-02-17 at 10 06 12](https://user-images.githubusercontent.com/81025586/154442803-1b5e98a2-fcac-42a2-ac19-e24ada1159a8.png)

**Comment by DigitalKnight0** [comment]
@BlizZard-bot made a issue over at #29 with the details

**Comment by DigitalKnight0** [comment]
@ManonLef feel free to go for it! Looks good to me

**Comment by DigitalKnight0** [comment]
@ManonLef I had one more solution regarding the buttons that might work. The current design looks good indeed, but it falls out with the test of the page design. I will create an issue with the design i have in mind and let you know!
