### ISSUE TITLE
Variable names not descriptive in js file. 

### ISSUE THREAD

**Issue by JJJ4032002** [Mclilzee/zap-simulator#25]
There are several variables such as **_ind , o_tier , c_tier_** which are not descriptive enough. I think they should be change to something like **_FormBtnNum, offence_tier , afterOffence_tier_**. They are long but are descriptive enough. If enough people approves this than i can make changes.

**Comment by Mclilzee** [comment]
Go for it, uncle bob's boy scouts rule

**Comment by JJJ4032002** [comment]
@BlizZard-bot sorry for the late response. I am a little busy with some other stuff right now. So you can take it up if you want.

**Comment by JJJ4032002** [comment]
Its ok i will look into it later.

**Comment by mgrigoriev8109** [comment]
@LeoKirasic I can pick this up.

**Comment by LeoKirasic** [comment]
@mgrigoriev8109 All yours!

**Comment by JJJ4032002** [comment]
@mgrigoriev8109 thanks for taking it up though I have changed some variable names where I found suitable and created a pull request. If you want you can see my changes too and see if it can be better.

**Comment by LeoKirasic** [comment]
This has been addressed in a PR, closing.
