### ISSUE TITLE
Implement disclaimer message

### ISSUE THREAD

**Issue by Mclilzee** [Mclilzee/zap-simulator#27]
We can change the footer text to say : This is an unofficial tool to visualize the zap matrix. For the official implementation, please visit this link and defer to the moderation team.

Or we can implement a starting screen that says this and a button which says "Understood" to start using the sim.

**Comment by DigitalKnight0** [comment]
I think the footer could prolly stay with some wording change to house the matrix link. Alongside that, we could perhaps add a popup on load with the disclamer message

**Comment by Mclilzee** [comment]
Ah i forgot to close this with my commit message
