### ISSUE TITLE
Save theme selection in local storage

### ISSUE THREAD

**Issue by Mclilzee** [Mclilzee/zap-simulator#31]
Save the latest chosen theme in a local storage. Make theme persist every visit without having to change it every time a user goes to the website.

**Comment by DigitalKnight0** [comment]
@LeoKirasic yours!

**Comment by Mclilzee** [comment]
@LeoKirasic alright you got this!

**Comment by JuanDCeballos** [comment]
Hi, I would like to give this a try.

**Comment by Mclilzee** [comment]
@JuanDCeballos all yours.

**Comment by LeoKirasic** [comment]
This has been addressed in a PR.
