### ISSUE TITLE
Change button wording

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#32]
Currently, the offense buttons do not reflect the corresponding offenses particularly such as `illegal activities`. They need bit of changing

Tasks: 
- [ ] Update the wording of the buttons to better reflect the offenses in each tier

**Comment by scheals** [comment]
I can take this on. do we want the offences to be more verbose or in the vein of "You/I have talked about illegal activities"?

**Comment by Mclilzee** [comment]
@scheals you got this. I don't think we need it to be verbose, but make it more clear. For example, there are Self promotion under spam offense, one guarantees a ban and another only gives you 2 zaps. Knowing the differentiation between them is important.
