### ISSUE TITLE
Fix font sizes

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#33]
Issue: 
The current font sizes are pretty inconsistent with no particular patterns. Plus they are not responsive

Tasks:
- [ ] The fonts should be consistent.
- [ ] Fonts should be responsive

**Comment by DigitalKnight0** [comment]
That's a lot for a single issue i guess

**Comment by Mclilzee** [comment]
@BlizZard-bot you working on this?
