### ISSUE TITLE
Refactor code to split the views and model/data

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#42]
This is to refactor the code based on the suggestions from discord, and will start as soon as we have a stable version

**Comment by Ishmam156** [comment]
Hey this is Hoody from discord and I would like to be one of the person working on this as per the conversation over there :)

**Comment by LeoKirasic** [comment]
@Ishmam156 Assigned :)

**Comment by takinabradley** [comment]
I'm willing to get started on this, if nobody else is too deep into it yet!
