### ISSUE TITLE
Adjust button width

### ISSUE THREAD

**Issue by DigitalKnight0** [Mclilzee/zap-simulator#49]
The current modal has buttons that are not equal in width which makes them odd

This fix should:
- [ ] Make the buttons have the same width
![Screenshot_2022_0301_183132](https://user-images.githubusercontent.com/93139167/156178298-7944837c-50fc-4512-87af-19af10bddaf2.jpg)

**Comment by bananabread08** [comment]
What do you think about these buttons @DigitalKnight0 ? I used `clamp()` for the width so they grow/shrink if needed. 
![Zap simulator](https://user-images.githubusercontent.com/73266502/156315115-6877deb6-e45a-4885-bdf7-9b310b6eecfa.png)

**Comment by Mclilzee** [comment]
Was fixed in this merge https://github.com/Mclilzee/zap-simulator/pull/50
